'use strict';

const express = require('express');

const { loadConfig } = require('./config');
const { loadMetricRequirements } = require('./metricRequirements');
const { SessionManager, HttpError } = require('./session');

const PORT = Number(process.env.PORT || 3001);

const app = express();
app.use(express.json());

const session = new SessionManager();

// Config is read once at startup (SPEC: "reads semconv-checker.config.yaml at
// startup"). Restart the backend to pick up changes.
let config;
try {
  config = loadConfig();
  console.log(
    `[backend] config loaded: expected_metrics=${config.expected_metrics.length} ` +
      `namespaces=${JSON.stringify(config.namespaces)}`,
  );
} catch (err) {
  console.error(`[backend] failed to load config: ${err.message}`);
  config = { expected_metrics: [], ignored_metrics: [], namespaces: [] };
}

// Metric requirement levels / stability / attributes for the "what is missing?"
// tab. Generated by `npm run fetch-metric-requirements`, read once at startup.
let metricRequirements;
try {
  metricRequirements = loadMetricRequirements();
  console.log(`[backend] metric-requirements loaded: ${Object.keys(metricRequirements).length} metrics`);
} catch (err) {
  console.error(`[backend] failed to load metric-requirements: ${err.message}`);
  metricRequirements = {};
}

const wrap = (fn) => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);

app.get('/api/health', (_req, res) => {
  res.status(200).json({ status: 'ok' });
});

app.get('/api/config', (_req, res) => {
  res.json(config);
});

app.get('/api/session', wrap(async (_req, res) => {
  res.json(await session.view());
}));

app.post('/api/session/start', wrap(async (_req, res) => {
  await session.start();
  res.status(200).json(await session.view());
}));

app.post('/api/session/stop', wrap(async (_req, res) => {
  await session.stop();
  res.status(200).json(await session.view());
}));

app.get('/api/report', (_req, res) => {
  const report = session.report(config, metricRequirements);
  if (!report) {
    res.status(404).json({ error: 'no report available' });
    return;
  }
  res.json(report);
});

// eslint-disable-next-line no-unused-vars
app.use((err, _req, res, _next) => {
  const status = err instanceof HttpError ? err.status : 500;
  if (status >= 500) console.error(`[backend] ${err.stack || err.message}`);
  res.status(status).json({ error: err.message });
});

async function main() {
  await session.init();
  app.listen(PORT, () => {
    console.log(`[backend] listening on :${PORT}`);
  });
}

main().catch((err) => {
  console.error(`[backend] fatal: ${err.stack || err.message}`);
  process.exit(1);
});
