'use strict';

// Loads src/data/metric-requirements.json (generated by
// scripts/fetch-metric-requirements.js). The backend uses it to label and
// filter never-emitted metrics in the "what is missing?" tab:
//   - drop opt_in metrics from that tab (unless in expected_metrics)
//   - attach a stability badge and required/recommended attribute chips
//
// File shape (SPEC § Scripts):
//   metrics:  { "<name>": "required" | "recommended" | "opt_in" }   -- flat, per SPEC
//   details:  { "<name>": { stability, attributes: [ {name, requirement_level} ] } }  -- additive
// This loader merges the two into { "<name>": { requirement_level, stability, attributes[] } }.
// It also accepts a legacy form where `metrics["<name>"]` is already that object.
// Missing metric -> caller falls back to "recommended" (SPEC § Scripts).

const fs = require('node:fs');
const path = require('node:path');

const REQUIREMENTS_PATH = process.env.METRIC_REQUIREMENTS_PATH
  || path.join(__dirname, 'data', 'metric-requirements.json');

const VALID_LEVELS = new Set(['required', 'recommended', 'opt_in']);

function cleanAttributes(attrs) {
  return Array.isArray(attrs)
    ? attrs.filter((a) => a && typeof a.name === 'string' && typeof a.requirement_level === 'string')
    : [];
}

function loadMetricRequirements(pathOverride) {
  const p = pathOverride || REQUIREMENTS_PATH;
  let raw;
  try {
    raw = fs.readFileSync(p, 'utf8');
  } catch (err) {
    if (err.code === 'ENOENT') {
      console.warn(`[backend] metric-requirements.json not found at ${p} — missing tab will fall back to "recommended"`);
      return {};
    }
    throw err;
  }

  const doc = JSON.parse(raw) || {};
  const metrics = doc.metrics && typeof doc.metrics === 'object' ? doc.metrics : {};
  const details = doc.details && typeof doc.details === 'object' ? doc.details : {};

  const out = {};
  for (const [name, value] of Object.entries(metrics)) {
    let level = 'recommended';
    let stability = 'development';
    let attributes = [];

    if (typeof value === 'string') {
      if (VALID_LEVELS.has(value)) level = value;
      const d = details[name];
      if (d && typeof d === 'object') {
        if (typeof d.stability === 'string') stability = d.stability;
        attributes = cleanAttributes(d.attributes);
      }
    } else if (value && typeof value === 'object') {
      // legacy: the whole entry lives under metrics[name]
      if (VALID_LEVELS.has(value.requirement_level)) level = value.requirement_level;
      if (typeof value.stability === 'string') stability = value.stability;
      attributes = cleanAttributes(value.attributes);
    }

    out[name] = { requirement_level: level, stability, attributes };
  }
  return out;
}

module.exports = { loadMetricRequirements, REQUIREMENTS_PATH };
