'use strict';

/*
 * Phase-06 — assertion 10: the "what is missing?" tab shows the metric
 * requirement level (from metric-requirements.json, generated by
 * scripts/fetch-metric-requirements.js) on each never-emitted metric card.
 *
 * One ordered walk, sharing a single page (mirrors the phase-05 harness):
 *
 *   idle --[click #main-btn]--> listening --[emit phase-05 OTLP]--> --[click stop]--> report
 *        --[click the "what is missing?" tab]--> missing tab
 *
 * The walk itself (start / emit / stop / report-ready / tab switch) is QA
 * infrastructure, not a phase assertion. It runs in beforeAll and writes
 * test-results/walk-status.json; validate.js reads that file and reports a walk
 * failure as assertion 99 ("not a phase failure") rather than failing the phase.
 *
 * beforeAll also fetches GET /api/report and records report.missing[] plus the
 * requirement_level the backend attached to the http.client.request.duration
 * entry, so assertion 10 cross-checks the API against the rendered chip.
 *
 * Selectors mirror references/prototype-2026-04-15.html and MissingCard.jsx:
 *   .ecard.missing                 never-emitted registry signal card
 *     .ename                       metric name
 *     .mlevel (.mlevel-recommended / .mlevel-required / .mlevel-opt_in)
 *                                  requirement-level pill, text = level label
 */

const { test, expect } = require('playwright/test');
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const BASE = process.env.PHASE6_BASE_URL || 'http://localhost:8080';
const OTLP = process.env.PHASE6_OTLP_ENDPOINT || 'http://localhost:4318';
const TEST_APP = path.join(__dirname, '..', '..', 'test-app', 'index.js');
const WALK_STATUS = path.join(__dirname, '..', 'test-results', 'walk-status.json');

const TARGET = 'http.client.request.duration';

function writeWalk(obj) {
  fs.mkdirSync(path.dirname(WALK_STATUS), { recursive: true });
  fs.writeFileSync(WALK_STATUS, JSON.stringify(obj, null, 2));
}

const ctx = {
  /** @type {string[]} */ missingNames: [],
  /** @type {string|null} */ apiLevel: null,
  rawMissingCount: -1,
};

test.describe.serial('phase-6 missing-tab requirement level', () => {
  /** @type {import('playwright/test').Page} */
  let page;

  test.beforeAll(async ({ browser }) => {
    test.setTimeout(360_000);
    try {
      page = await browser.newPage();
      await page.goto(BASE, { waitUntil: 'domcontentloaded' });
      await expect(page.locator('#status-badge')).toBeVisible({ timeout: 30_000 });

      // idle -> listening (start blocks on weaver boot + collector restart)
      await page.locator('#main-btn').click();
      await expect(page.locator('#status-badge')).toHaveText(/listening/i, { timeout: 200_000 });
      await expect(page.locator('#main-btn.btn-stop')).toBeVisible();

      // emit the phase-05 scenario (marks the http namespace active so the
      // missing tab is populated with http.* registry metrics)
      const out = execFileSync(
        'node',
        [TEST_APP, '--scenario', 'phase-05', '--endpoint', OTLP],
        { encoding: 'utf8', stdio: 'pipe' },
      );
      console.log(`[spec] test-app phase-05 emit:\n${out}`);
      await page.waitForTimeout(3000);

      // listening -> report (stop blocks while weaver flushes the report)
      await page.locator('#main-btn').click();
      await expect(page.locator('#status-badge')).toHaveText(/report ready/i, { timeout: 150_000 });

      await expect(page.locator('.pane-report')).toBeVisible({ timeout: 30_000 });
      await expect(page.locator('.ecard').first()).toBeVisible({ timeout: 30_000 });

      // API cross-check: the backend attaches requirement_level per missing metric
      const repRes = await page.request.get(`${BASE}/api/report`);
      console.log(`[spec] GET /api/report -> HTTP ${repRes.status()}`);
      const report = await repRes.json();
      const missing = Array.isArray(report.missing) ? report.missing : [];
      ctx.rawMissingCount = missing.length;
      ctx.missingNames = missing.map((m) => m && m.name).filter(Boolean);
      const entry = missing.find((m) => m && m.name === TARGET);
      ctx.apiLevel = entry ? (entry.requirement_level || null) : null;
      console.log(`[spec] report.missing (${ctx.rawMissingCount}); ${TARGET} requirement_level=${JSON.stringify(ctx.apiLevel)}`);

      // switch to the "what is missing?" tab (second tab)
      const missingTab = page.locator('.tab-bar .tab').nth(1);
      await missingTab.click();
      await expect(missingTab).toHaveClass(/active/);
      await expect(page.locator('.ecard.missing').first()).toBeVisible({ timeout: 15_000 });

      writeWalk({
        ok: true,
        rawMissingCount: ctx.rawMissingCount,
        missingNames: ctx.missingNames,
        apiLevel: ctx.apiLevel,
      });
    } catch (err) {
      writeWalk({ ok: false, error: String((err && err.stack) || err) });
      throw err;
    }
  });

  test.afterAll(async () => {
    if (page) await page.close();
  });

  function missingCard(name) {
    return page.locator('.ecard.missing').filter({
      has: page.locator('.ename', { hasText: new RegExp(`^${name.replace(/\./g, '\\.')}$`) }),
    });
  }

  test('10. Missing tab shows the "recommended" requirement level on the http.client.request.duration card', async () => {
    // API truth: the backend labelled the missing metric "recommended"
    expect(ctx.missingNames).toContain(TARGET);
    expect(ctx.apiLevel).toBe('recommended');

    // UI: the card carries a .mlevel pill reading "recommended"
    const card = missingCard(TARGET);
    await expect(card).toHaveCount(1);
    const mlevel = card.locator('.mlevel');
    await expect(mlevel).toHaveText(/^recommended$/);
    await expect(mlevel).toHaveClass(/\bmlevel-recommended\b/);
  });
});
